### ISSUE TITLE
Can I report here the erratas in the book?

### ISSUE THREAD

**Issue by juananpe** [AndreaCirilloAC/r_data_mining#1]
Hi,

  I know that the packt website has a section for reporting erratas to the book but:

* it lacks direct communication with the author
* tracking of the errata (comments, discussion, triaging...)

Can I report them here as "bugs" or "issues"? Thanks.

**Comment by AndreaCirilloAC** [comment]
Hi @juananpe , thank you for the detailed errata you posted. You are right about Packt errata system, nevertheless at the moment that is the best way:

- to make the other readers acknowledged of them
- to make them being taken into consideration for the next editions

I would therefore kindly ask you to submit the list to them as well.

That said I will leverage your list to fix on the repo the errata related to code.
So thank you for your contribution.

**Comment by juananpe** [comment]
Done
